Pass `double`s to `pow()` for Solaris (#196)
Since calling `pow(int, int)` is undefined on that platform and results in:

duration.cpp:1143:87: error: call of overloaded ‘pow(int, int)’ is ambiguous
   static int64_t DOUBLE_MAX_NO_LOSS = static_cast<int64_t>(pow(FLT_RADIX, DBL_MANT_DIG) - 1);
                                                                                       ^
In file included from /usr/include/math.h:15:0,
                 from /opt/csw/include/c++/5.2.0/cmath:44,
                 from /opt/csw/include/c++/5.2.0/random:38,
                 from /opt/csw/include/c++/5.2.0/bits/stl_algo.h:66,
                 from /opt/csw/include/c++/5.2.0/algorithm:62,
                 from ../inst/include/date/date.h:44,
                 from clock.h:5,
                 from duration.cpp:1:
/opt/csw/lib/gcc/i386-pc-solaris2.10/5.2.0/include-fixed/iso/math_iso.h:204:21: note: candidate: long double std::pow(long double, long double)
  inline long double pow(long double __X, long double __Y) { return
                     ^
/opt/csw/lib/gcc/i386-pc-solaris2.10/5.2.0/include-fixed/iso/math_iso.h:171:15: note: candidate: float std::pow(float, float)
  inline float pow(float __X, float __Y) { return __powf(__X, __Y); }
               ^
/opt/csw/lib/gcc/i386-pc-solaris2.10/5.2.0/include-fixed/iso/math_iso.h:72:15: note: candidate: double std::pow(double, double)
 extern double pow __P((double, double));